#!/bin/bash

# This script passes system environment variables to Vite
source ~/.zshrc

# Pass the environment variables to the Vite dev server
VITE_SUPABASE_URL_IND=$SUPABASEURLIND \
VITE_SUPABASE_SERVICE_KEY_IND=$SUPABASESERVICEKEYIND \
VITE_SUPABASE_API_KEY_IND=$SUPABASEAPIKEYIND \
VITE_SUPABASE_SECRET_KEY_IND=$SUPABASESECRETKEYIND \
VITE_DEV_API_URL=$BASE_API_URL_DEV_IND \
VITE_PROD_API_URL=$BASE_API_URL_PROD_IND \
npm run dev