import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAIIND")
PINECONE_API_KEY = os.getenv("PINECONEIND")
SUPABASE_URL = os.getenv("SUPABASEURLIND")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASESERVICEKEYIND")
SUPABASE_API_KEY = os.getenv("SUPABASEAPIKEYIND")
FROM_EMAIL = os.getenv("FROMEMAILIND")
TO_EMAIL = os.getenv("TOEMAILIND")
MAILERSEND_API_KEY = os.getenv("MAILERSENDAPIKEYIND")
FROM_NAME = os.getenv("FROMNAMEIND")
